#!/usr/bin/env python
import sys
import plistlib as plist

# Read args from ARGV
dest, path, token = sys.argv[1:]

# Read plist
data = plist.readPlist(dest)

# Update MY_PATH, GITHUB_TOKEN
data['variables']['MY_PATH'] = path
data['variables']['GITHUB_TOKEN'] = token

# Write updated plist
plist.writePlist(data, dest)

sys.exit(0)
